# Generated by Django 5.2.6 on 2025-09-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Encargado', 'Encargado'), ('Panadero', 'Panadero'), ('Cajero', 'Cajero')], max_length=20),
        ),
    ]
