# Generated by Django 5.2.6 on 2025-09-28 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Storage',
                'verbose_name_plural': 'User Storages',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
