# Generated by Django 5.2.6 on 2025-10-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_purchase_approved_at_purchase_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
