# Generated by Django 5.2.6 on 2025-10-20 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cashmovement_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ingredient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('u', 'Unidades')], default='u', max_length=10),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('u', 'Unidades')], default='g', max_length=10)),
                ('ingredient', models.ForeignKey(limit_choices_to={'is_ingredient': True}, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='api.product')),
            ],
        ),
    ]
