# Generated by Django 5.2.6 on 2025-10-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_inventorychange_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidades', 'Unidades')], default='unidades', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('unidades', 'Unidades')], default='g', max_length=10),
        ),
    ]
