# Generated by Django 5.2.6 on 2025-11-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_product_deleted_at_product_is_active_and_more'),
    ]

    operations = [
    ]
