# Generated by Django 5.2.6 on 2025-11-06 04:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_create_resettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
