# Generated by Django 5.2.6 on 2025-11-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high_stock_multiplier',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
    ]
