# Generated by Django 5.2.6 on 2025-12-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_product_high_stock_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lock_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10, null=True),
        ),
    ]
