# Generated by Django 5.2.6 on 2025-12-13 19:27

from django.db import migrations


def fix_null_lock_types(apps, schema_editor):
    """
    Actualizar todos los usuarios bloqueados que tienen lock_type NULL
    a 'automatic' (ya que fueron bloqueados antes de agregar el campo)
    """
    User = apps.get_model('api', 'User')
    
    # Actualizar usuarios bloqueados sin lock_type
    updated = User.objects.filter(
        is_locked=True,
        lock_type__isnull=True
    ).update(lock_type='automatic')
    
    print(f"✅ Actualizados {updated} usuarios con lock_type NULL a 'automatic'")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_add_lock_type_to_user'),
    ]

    operations = [
        migrations.RunPython(fix_null_lock_types, migrations.RunPython.noop),
    ]
