# Generated by Django 5.2.6 on 2025-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_fix_null_lock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fecha_para_la_que_se_quiere_el_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
