# Generated by Django 5.2.6 on 2025-12-17 19:22
# Empty migration - fields already exist with correct names

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_fecha_para_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-fecha_de_orden_del_pedido']},
        ),
    ]
